name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
      with:
        run: |
          cd $GITHUB_WORKSPACE
          docker build -t vanzan2015/remnux-ubuntu-14.04 .
          docker run vanzan2015/remnux-ubuntu-14.04
